#!/usr/bin/env bash

declare name="${1}"

while [[ -z ${name} ]]; do
  read -p 'Name: ' name
done

echo "Setting up new middleware ${name}"

declare -r package_dir="./packages/${name:?}"

mkdir "${package_dir:?}"
echo '{
  "plugins": [
    "chai-friendly"
  ],
  "env": {
    "mocha": true,
    "node": true
  },
  "rules": {
    "jsx-quotes": ["error", "prefer-single"],
    "no-unused-vars": ["error", { "argsIgnorePattern": "^_" }]
  },
  "extends": ["standard", "plugin:chai-friendly/recommended"]
}
' > "${package_dir:?}/.eslintrc.json" || exit

cd "${package_dir:?}" || exit
npm init

echo 'Setting up linters'
npm install --save-dev \
      eslint \
      eslint-config-standard \
      eslint-plugin-promise \
      eslint-plugin-import \
      eslint-plugin-chai-friendly \
      eslint-plugin-node \
      prettier-eslint

echo 'Setting up test harness'
npm install --save-dev \
      mocha \
      chai

cd -

echo 'Creating boilerplate'

echo "# ${name:?}

...

## Options

| Name | Required | Default value | Description |
| ---- | -------- | ------------- | ----------- |
| -    | -        | -             | -           |
" > "${package_dir:?}/README.md"

echo "const middleware = require('./middleware.js')
module.exports = middleware

" > "${package_dir:?}/index.js"

echo "const defaults = {}

module.exports = options => {
  options = { ...defaults, ...options }

  const middleware = (req, res, next) => {
    next()
  }

  middleware.options = options
  return middleware
}
" > "${package_dir:?}/middleware.js"

echo "const expect = require('chai').expect
const middleware = require('./middleware')

describe('${name}', () => {
  it('has a test', () => {
    expect(true).to.equal(true)
  })
})
" > "${package_dir:?}/middleware.spec.js"

echo
echo 'NOTE: Add the following lines as npm scripts'
echo
echo "    \"test\": \"mocha './{,!(node_modules)/**/}*.spec.js' --reporter spec --slow 10\","
echo "    \"test:watch\": \"mocha './{,!(node_modules)/**/}*.spec.js' --reporter spec --watch --slow 10\""
