#!/usr/bin/env bash

while (! npm whoami 2>&1) 1>/dev/null;
do
    npm login
done

for package in $(ls ./packages/); do
  echo "${package:?}"
  declare package_dir="./packages/${package:?}"
  if [[ -d ${package_dir:?} ]]; then
    cd "${package_dir:?}"
    npm publish
    cd -
  fi
done